### PR TITLE
Add support for VSCode JavaScript React and TypeScript Language

### PR DESCRIPTION
**Pull request by zachgibson**

### CODE REVIEW

**Review by paulmolluzzo — APPROVED** [review]
Looks great! Thanks! 🙌

**Comment by paulmolluzzo** [comment]
I just published `v1.1.0`. Not sure how long it'll take to show up in the marketplace tho 🤷‍♂️

**Comment by paulmolluzzo** [comment]
that was fast 😄

**Comment by zachgibson** [comment]
Awesome! 😄

**Pull request merged**
